### ISSUE TITLE
Integration with Jquery

### ISSUE THREAD

**Issue by manutheblacker** [3dlook-me/saia-sdk#10]
Hello guys, i've a customer who is going to use your solution, but unfortunately after a full lookup of the api, i've not found any  way to use the package into my website using WordPress. If he exists a way to use it with jQuery please lead me the way to do it.

**Comment by anatolii-pisarivskyi** [comment]
@manutheblacker Please follow out [build instruction](https://github.com/3dlook-me/saia-sdk#building) to get a pre-build and minified version of SAIA-SDK, which you could include to your WordPress website and use in your scripts

**Comment by manutheblacker** [comment]
Thank you for your quick response, i'll follow the documentation to do it.
